//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace MyPrime
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class PrimeEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“PrimeEntities”部分中的连接字符串初始化新 PrimeEntities 对象。
        /// </summary>
        public PrimeEntities() : base("name=PrimeEntities", "PrimeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 PrimeEntities 对象。
        /// </summary>
        public PrimeEntities(string connectionString) : base(connectionString, "PrimeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 PrimeEntities 对象。
        /// </summary>
        public PrimeEntities(EntityConnection connection) : base(connection, "PrimeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Prime> Prime
        {
            get
            {
                if ((_Prime == null))
                {
                    _Prime = base.CreateObjectSet<Prime>("Prime");
                }
                return _Prime;
            }
        }
        private ObjectSet<Prime> _Prime;

        #endregion

        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Prime EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToPrime(Prime prime)
        {
            base.AddObject("Prime", prime);
        }

        #endregion

    }

    #endregion

    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PrimeModel", Name="Prime")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Prime : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Prime 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        public static Prime CreatePrime(global::System.Int64 id)
        {
            Prime prime = new Prime();
            prime.Id = id;
            return prime;
        }

        #endregion

        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PrimeNumber
        {
            get
            {
                return _PrimeNumber;
            }
            set
            {
                OnPrimeNumberChanging(value);
                ReportPropertyChanging("PrimeNumber");
                _PrimeNumber = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PrimeNumber");
                OnPrimeNumberChanged();
            }
        }
        private global::System.String _PrimeNumber;
        partial void OnPrimeNumberChanging(global::System.String value);
        partial void OnPrimeNumberChanged();

        #endregion

    
    }

    #endregion

    
}
